modLoader = "mclibprovider"
loaderVersion = "[1,)"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/lhns/mc-skylands/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Skylands"
authors = "lhns"
description = '''
Adds a Skylands dimension reachable by climbing a beanstalk through the clouds.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
